### ISSUE TITLE
socket.removeAllListeners() prevent the process to exit.

### ISSUE THREAD

**Issue by ribizli** [hbenl/mpc-js-node#2]
I think by `socket.removeAllListeners()` some internal cleanup handler is also removed, so the `socket.end()` call won't really close every resources preventing the app to exit gracefully.
I tried in debugger to call the `socket.end()` before, so the app quits normally.

I think only the handlers attached by the `SocketWrapper` should be removed.

See this note in the Node.js docs:

> Note that it is bad practice to remove listeners added elsewhere in the code, particularly when the EventEmitter instance was created by some other component or module (e.g. sockets or file streams).

**Comment by hbenl** [comment]
Indeed. Thanks for figuring this out, I wasn't aware of it (and the Socket documentation doesn't mention it...).
